name: Build and deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g sass autoprefixer postcss postcss-cli
      - run: sass ./src/sass/main.scss ./src/sass/main.css --style compressed
      - run: postcss ./src/sass/main.css --use autoprefixer -d ./src/css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          exclude_assets: 'sass'
