name: Build and deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Make destination directory for compiled CSS
        run: mkdir -vp src/css/
      - name: Build
        uses: gha-utilities/sass-build@v0.4.4
        with:
          source: src/sass/main.scss
          destination: src/css/main.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          exclude_assets: 'sass'